'use client';

import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, CalendarDays } from 'lucide-react';
import AppShell from '@/components/AppShell';
import { useEdoAccount } from '@/hooks/useEdoAccount';
import { supabase } from '@/lib/supabase';
import type { EdoLedger, EdoTransaction } from '@/lib/types';

export default function LedgerPage() {
  const { access, loading, error } = useEdoAccount();
  const [ledgers, setLedgers] = useState<EdoLedger[]>([]);
  const [transactions, setTransactions] = useState<EdoTransaction[]>([]);

  useEffect(() => { if (!access) return; Promise.all([supabase.from('edo_monthly_ledgers').select('*').order('month_start', { ascending: false }), supabase.from('edo_transactions').select('*').eq('status','APPROVED').order('occurred_on',{ ascending:false })]).then(([ledger, tx]) => { setLedgers((ledger.data as EdoLedger[]) ?? []); setTransactions((tx.data as EdoTransaction[]) ?? []); }); }, [access]);

  return <AppShell><main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-8"><div className="mb-5"><div className="text-xs font-black uppercase tracking-[.2em] text-lime-300">Monthly ledger</div><h1 className="mt-1 text-3xl font-black">EDO balance history</h1><p className="mt-1 text-sm text-slate-500">Month-end balances with the approved effective order.</p></div>{loading ? <Card text="Loading ledger…"/> : error ? <Card text={error}/> : <div className="space-y-4">{ledgers.length ? ledgers.map((ledger) => { const monthTx = transactions.filter((tx) => tx.occurred_on.slice(0,7) === ledger.month_start.slice(0,7)).sort((a,b) => (a.effective_order ?? 999) - (b.effective_order ?? 999)); return <details key={ledger.id} className="glass-card rounded-3xl" open={ledgers[0]?.id === ledger.id}><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/5 text-lime-300"><CalendarDays className="h-5 w-5"/></span><div><div className="font-black">{new Date(`${ledger.month_start}T00:00:00`).toLocaleDateString('en-SG',{month:'long',year:'numeric'})}</div><div className="text-xs text-slate-500">Opening {Number(ledger.opening_balance).toFixed(1)}h · +{Number(ledger.approved_grants).toFixed(1)}h · -{Number(ledger.approved_claims).toFixed(1)}h</div></div></div><div className="text-right"><div className="text-xl font-black">{Number(ledger.closing_balance).toFixed(1)}h</div><div className={`text-[10px] font-black ${ledger.warning_level === 'CRITICAL' ? 'text-rose-300' : ledger.warning_level === 'WARNING' ? 'text-amber-200' : 'text-lime-300'}`}>{ledger.warning_level}</div></div></summary><div className="border-t border-white/5 px-5 pb-5 sm:px-6 sm:pb-6">{monthTx.length ? <div className="divide-y divide-white/5">{monthTx.map((tx) => <div key={tx.id} className="flex items-center gap-3 py-3"><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${tx.transaction_type === 'GRANT' ? 'bg-lime-300/10 text-lime-300' : 'bg-sky-300/10 text-sky-300'}`}>{tx.transaction_type === 'GRANT' ? <ArrowUpRight className="h-4 w-4"/> : <ArrowDownRight className="h-4 w-4"/>}</span><div className="min-w-0 flex-1"><div className="font-bold">#{tx.effective_order ?? '–'} · {tx.transaction_type} {Number(tx.hours).toFixed(1)}h</div><div className="text-xs text-slate-500">{tx.occurred_on} · {tx.event_id}</div>{tx.processing_note ? <div className="mt-1 text-xs font-bold text-amber-200">{tx.processing_note}</div> : null}</div><div className="text-sm font-black">{tx.running_balance == null ? '–' : `${Number(tx.running_balance).toFixed(1)}h`}</div></div>)}</div> : <div className="pt-5 text-sm text-slate-500">No approved entries in this month.</div>}</div></details>; }) : <Card text="No month-end ledger has been calculated yet. It will appear after the first approval."/>}</div>}</main></AppShell>;
}
function Card({ text }: { text: string }) { return <div className="glass-card rounded-3xl p-6 text-sm text-slate-300">{text}</div>; }
