-- Production telemetry store applied to Supabase.
-- Kept in-repo so the Prisma schema and production DDL remain auditable.
create table if not exists public."PerformanceMetric" (
  id bigint generated by default as identity primary key,
  source text not null,
  route text not null,
  metric text not null,
  value double precision not null,
  rating text,
  release text,
  "navigationType" text,
  metadata jsonb,
  "createdAt" timestamptz not null default now()
);

create index if not exists "PerformanceMetric_createdAt_idx"
  on public."PerformanceMetric" ("createdAt" desc);

create index if not exists "PerformanceMetric_route_metric_createdAt_idx"
  on public."PerformanceMetric" (route, metric, "createdAt" desc);

alter table public."PerformanceMetric" enable row level security;
