import Link from 'next/link';
import { Clock3, Pencil, ShieldAlert, Trophy } from 'lucide-react';

type PendingItem={id:string;name:string;column:string;category:string;points:number;createdAt:Date};

export default function AdminQueueBoard({pendingCount,correctionCount,duplicateCount,dirtyWeekCount,pendingItems}:{pendingCount:number;correctionCount:number;duplicateCount:number;dirtyWeekCount:number;pendingItems:PendingItem[]}){
  const total=pendingCount+correctionCount+duplicateCount+dirtyWeekCount;
  return <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 sm:p-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-sky-300">Today&apos;s queue</p><h2 className="mt-2 text-xl font-black">One place for work that needs attention</h2><p className="mt-1 text-sm text-slate-500">{total?`${total} queue item${total===1?'':'s'} across reviews, corrections, duplicates and finalized weeks.`:'No outstanding operational work in the tracked queues.'}</p></div><Link href="/admin/activities" className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold text-slate-300 hover:border-sky-300/30">Open activity review</Link></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><QueueCard href="/admin/activities" icon={<Clock3 className="h-5 w-5"/>} label="Pending activities" value={pendingCount} detail="Oldest first in review"/><QueueCard href="/admin/corrections" icon={<Pencil className="h-5 w-5"/>} label="Corrections" value={correctionCount} detail="Approved entries awaiting decision"/><QueueCard href="/admin/duplicates" icon={<ShieldAlert className="h-5 w-5"/>} label="Duplicates" value={duplicateCount} detail="Possible duplicate pairs"/><QueueCard href="/admin/awards" icon={<Trophy className="h-5 w-5"/>} label="Weeks to rebuild" value={dirtyWeekCount} detail="Finalized results marked stale"/></div>
    {pendingItems.length?<div className="mt-5 overflow-hidden rounded-xl border border-white/10"><div className="flex items-center justify-between bg-black/15 px-4 py-3"><p className="text-sm font-black">Next pending reviews</p><span className="text-xs text-slate-500">Oldest first</span></div><div className="divide-y divide-white/5">{pendingItems.map(item=><Link key={item.id} href={`/admin/activities?activity=${item.id}`} className="grid gap-1 px-4 py-3 transition hover:bg-white/[0.03] sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-sm font-bold">{item.name} · {friendlyCategory(item.category)}</p><p className="mt-1 text-xs text-slate-500">{item.column} · submitted {item.createdAt.toLocaleString('en-SG',{timeZone:'Asia/Singapore',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</p></div><span className="text-sm font-black text-orange-300">{item.points.toFixed(1)} pts</span></Link>)}</div></div>:null}
  </section>;
}

function QueueCard({href,icon,label,value,detail}:{href:string;icon:React.ReactNode;label:string;value:number;detail:string}){const attention=value>0;return <Link href={href} className={`rounded-xl border p-4 transition ${attention?'border-amber-400/20 bg-amber-400/[0.07] hover:border-amber-300/40':'border-white/10 bg-black/10 hover:border-white/20'}`}><span className={attention?'text-amber-300':'text-emerald-300'}>{icon}</span><p className="mt-3 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></Link>;}
function friendlyCategory(value:string){return value==='WALK_OR_HIKE'?'Walk / Hike':value==='TROOP_GAMES'?'Troop Games':value.charAt(0)+value.slice(1).toLowerCase();}
