'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Activity, BarChart3, DatabaseBackup, Download, FileClock, Megaphone, Plus, RefreshCw, Save, Settings, ShieldCheck, Trophy, Users, Wrench } from 'lucide-react';
import Navbar from '@/components/Navbar';
import SystemStatusCard from '@/components/SystemStatusCard';
import type { ScoringRules } from '@/lib/scoring';

type SettingsData = { id: string; challengeName: string; startDate: string; endDate: string; weeklyGoal: number; maintenanceMode: boolean; maintenanceMessage: string; scoringRules: ScoringRules; updatedAt: string };
type Announcement = { id: string; title: string; message: string; isActive: boolean; createdAt: string; updatedAt: string };
type Audit = { id: string; actorName: string; action: string; target: string; details: Record<string, unknown> | null; createdAt: string };
type Column = { id: string; name: string; isActive: boolean; memberCount: number; totalPoints: number };
type Analytics = { users: number; activities: number; pending: number; approvedPoints: number; categories: Array<{ category: string; count: number }> };

const ruleFields: Array<{ key: keyof ScoringRules; label: string; suffix: string }> = [
  { key: 'runBasePerKm', label: 'Run base', suffix: 'pts/km' }, { key: 'runFastBonusPerKm', label: 'Fast run bonus', suffix: 'pts/km' }, { key: 'runMediumBonusPerKm', label: 'Medium run bonus', suffix: 'pts/km' }, { key: 'runStandardBonusPerKm', label: 'Standard run bonus', suffix: 'pts/km' },
  { key: 'runFastPaceThreshold', label: 'Fast pace below', suffix: 'min/km' }, { key: 'runMediumPaceThreshold', label: 'Medium pace below', suffix: 'min/km' }, { key: 'runSlowPaceThreshold', label: 'Run converts to walk above', suffix: 'min/km' },
  { key: 'cycleKmPerPoint', label: 'Cycling distance per point', suffix: 'km' }, { key: 'swimMetersPerPoint', label: 'Swimming distance per point', suffix: 'm' }, { key: 'walkPointsPerKm', label: 'Walk / hike rate', suffix: 'pts/km' }, { key: 'walkMinimumKm', label: 'Minimum walk / hike', suffix: 'km' }, { key: 'troopGamePoints', label: 'Troop Games session', suffix: 'pts' }, { key: 'friendBonus', label: 'Friend bonus', suffix: 'pts' },
];

export default function AdminControlCenter({ settings, announcements, audit, columns, analytics }: { settings: SettingsData; announcements: Announcement[]; audit: Audit[]; columns: Column[]; analytics: Analytics }) {
  const router = useRouter();
  const [form, setForm] = useState({ challengeName: settings.challengeName, startDate: settings.startDate.slice(0, 10), endDate: settings.endDate.slice(0, 10), weeklyGoal: settings.weeklyGoal, maintenanceMode: settings.maintenanceMode, maintenanceMessage: settings.maintenanceMessage, scoringRules: settings.scoringRules });
  const [announcement, setAnnouncement] = useState({ title: '', message: '' });
  const [newColumn, setNewColumn] = useState('');
  const [columnDrafts, setColumnDrafts] = useState(() => Object.fromEntries(columns.map((column) => [column.id, { name: column.name, isActive: column.isActive }])));
  const [busy, setBusy] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  const action = async (name: string, payload: Record<string, unknown>, success: string) => {
    setBusy(name); setError(''); setMessage('');
    try {
      const response = await fetch('/api/admin/control', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: name, payload }) });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(typeof data.error === 'string' ? data.error : 'Admin action failed');
      setMessage(success); router.refresh(); return true;
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Admin action failed'); return false; }
    finally { setBusy(''); }
  };

  const saveSettings = () => action('settings.update', { ...form, weeklyGoal: Number(form.weeklyGoal), startDate: new Date(`${form.startDate}T00:00:00Z`).toISOString(), endDate: new Date(`${form.endDate}T23:59:59Z`).toISOString(), scoringRules: form.scoringRules }, 'Challenge settings saved. Use recalculation only if old scores should adopt the new rules.');
  const publish = async () => { if (await action('announcement.create', announcement, 'Announcement published.')) setAnnouncement({ title: '', message: '' }); };
  const addColumn = async () => { if (await action('column.create', { name: newColumn }, 'Column created.')) setNewColumn(''); };
  const recalculate = () => { if (window.confirm('Recalculate every activity and rebuild all standings using the current rules? This may change existing scores.')) action('scores.recalculate', { confirmation: 'RECALCULATE' }, 'Every activity and weekly standing was recalculated.'); };

  return <div className="min-h-screen bg-slate-950 text-white"><Navbar /><main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8 lg:py-12">
    <header className="rounded-3xl border border-white/10 bg-[radial-gradient(circle_at_top_left,_rgba(249,115,22,0.22),_transparent_45%),rgba(255,255,255,0.04)] p-6 sm:p-8"><p className="flex items-center gap-2 text-sm font-black uppercase tracking-[0.2em] text-orange-300"><ShieldCheck className="h-4 w-4" />Admin command</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-black sm:text-5xl">Competition control centre</h1><p className="mt-3 text-slate-400">Configure the challenge, communicate with athletes, and export operational data.</p></div><div className="flex gap-2"><Link href="/admin/activities" className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold">Review queue</Link><Link href="/admin/users" className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold">Manage users</Link></div></div></header>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<Users />} label="Participants" value={analytics.users.toString()} /><Stat icon={<Activity />} label="Activities" value={analytics.activities.toString()} /><Stat icon={<FileClock />} label="Pending review" value={analytics.pending.toString()} /><Stat icon={<Trophy />} label="Approved points" value={analytics.approvedPoints.toFixed(1)} /></div>
    {message ? <div role="status" className="rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-200">{message}</div> : null}{error ? <div role="alert" className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</div> : null}
    <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><Heading icon={<Settings />} title="Challenge settings" subtitle="Changes affect new activities immediately." /><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Challenge name"><input value={form.challengeName} onChange={(event) => setForm((current) => ({ ...current, challengeName: event.target.value }))} className="control-input" /></Field><Field label="Start date"><input type="date" value={form.startDate} onChange={(event) => setForm((current) => ({ ...current, startDate: event.target.value }))} className="control-input" /></Field><Field label="End date"><input type="date" value={form.endDate} onChange={(event) => setForm((current) => ({ ...current, endDate: event.target.value }))} className="control-input" /></Field><Field label="Minimum weekly goal"><input type="number" min="1" value={form.weeklyGoal} onChange={(event) => setForm((current) => ({ ...current, weeklyGoal: Number(event.target.value) }))} className="control-input" /></Field></div><div className="mt-6 rounded-2xl border border-amber-300/20 bg-amber-300/5 p-4"><div className="flex items-start gap-3"><Wrench className="mt-0.5 h-5 w-5 shrink-0 text-amber-300" /><div className="flex-1"><label className="flex items-center justify-between gap-4"><span><span className="block font-black text-amber-100">Maintenance mode</span><span className="mt-1 block text-xs text-slate-500">Pause participant uploads and submissions while keeping admin access available.</span></span><input type="checkbox" checked={form.maintenanceMode} onChange={(event) => setForm((current) => ({ ...current, maintenanceMode: event.target.checked }))} className="h-5 w-5 shrink-0 accent-amber-400" /></label><label className="mt-4 block text-xs font-semibold text-slate-400">Participant message<input value={form.maintenanceMessage} maxLength={240} onChange={(event) => setForm((current) => ({ ...current, maintenanceMessage: event.target.value }))} className="control-input" /></label></div></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{ruleFields.map((field) => <Field key={field.key} label={field.label} suffix={field.suffix}><input type="number" min="0" step="0.1" value={form.scoringRules[field.key]} onChange={(event) => setForm((current) => ({ ...current, scoringRules: { ...current.scoringRules, [field.key]: Number(event.target.value) } }))} className="control-input" /></Field>)}</div><div className="mt-6 flex justify-end"><button type="button" onClick={saveSettings} disabled={Boolean(busy)} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-black disabled:opacity-50"><Save className="h-4 w-4" />Save settings</button></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><Heading icon={<Megaphone />} title="Announcements" subtitle="Active notices appear throughout the app." /><div className="mt-5 space-y-3"><input value={announcement.title} onChange={(event) => setAnnouncement((current) => ({ ...current, title: event.target.value }))} placeholder="Announcement title" className="control-input" /><textarea value={announcement.message} onChange={(event) => setAnnouncement((current) => ({ ...current, message: event.target.value }))} rows={3} maxLength={500} placeholder="Message for all participants" className="control-input resize-none" /><button type="button" onClick={publish} disabled={Boolean(busy) || announcement.title.trim().length < 3 || announcement.message.trim().length < 3} className="rounded-xl bg-sky-500 px-4 py-2 text-sm font-black text-slate-950 disabled:opacity-40">Publish</button></div><div className="mt-5 space-y-2">{announcements.map((item) => <div key={item.id} className="rounded-xl border border-white/5 bg-black/10 p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{item.title}</p><p className="mt-1 text-sm text-slate-400">{item.message}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs ${item.isActive ? 'bg-emerald-400/10 text-emerald-300' : 'bg-white/5 text-slate-500'}`}>{item.isActive ? 'Live' : 'Paused'}</span></div><div className="mt-3 flex gap-3 text-xs"><button onClick={() => action('announcement.toggle', { id: item.id, isActive: !item.isActive }, item.isActive ? 'Announcement paused.' : 'Announcement activated.')} className="font-bold text-sky-300">{item.isActive ? 'Pause' : 'Activate'}</button><button onClick={() => window.confirm('Delete this announcement?') && action('announcement.delete', { id: item.id }, 'Announcement deleted.')} className="font-bold text-rose-300">Delete</button></div></div>)}</div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><Heading icon={<Users />} title="Columns" subtitle="Create, rename, activate or archive competition columns." /><div className="mt-5 flex gap-2"><input value={newColumn} onChange={(event) => setNewColumn(event.target.value)} placeholder="New column name" className="control-input" /><button type="button" onClick={addColumn} disabled={Boolean(busy) || newColumn.trim().length < 2} className="rounded-xl bg-sky-500 p-3 text-slate-950 disabled:opacity-40"><Plus className="h-5 w-5" /></button></div><div className="mt-5 space-y-2">{columns.map((column) => { const draft = columnDrafts[column.id]; return <div key={column.id} className="rounded-xl border border-white/5 bg-black/10 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><input value={draft.name} onChange={(event) => setColumnDrafts((current) => ({ ...current, [column.id]: { ...draft, name: event.target.value } }))} className="control-input" /><label className="flex shrink-0 items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={draft.isActive} onChange={(event) => setColumnDrafts((current) => ({ ...current, [column.id]: { ...draft, isActive: event.target.checked } }))} />Active</label><button onClick={() => action('column.update', { id: column.id, ...draft }, 'Column updated.')} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold">Save</button></div><p className="mt-2 text-xs text-slate-600">{column.memberCount} members · {column.totalPoints.toFixed(1)} points</p></div>; })}</div></section></div>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><Heading icon={<Download />} title="Data exports" subtitle="Download spreadsheets or a safe operational backup." /><div className="mt-5 grid gap-3 sm:grid-cols-2"><Export href="/api/admin/export?type=activities" label="Activities CSV" /><Export href="/api/admin/export?type=standings" label="Standings CSV" /><Export href="/api/admin/export?type=users" label="Users CSV" /><Export href="/api/admin/export?type=backup" label="Full backup JSON" icon={<DatabaseBackup className="h-4 w-4" />} /></div><p className="mt-3 text-xs leading-5 text-slate-600">The backup excludes passwords and connected-service tokens. It is intended for safekeeping and audit, not automatic restore.</p><div className="mt-6 rounded-xl border border-rose-400/20 bg-rose-400/5 p-4"><p className="font-bold text-rose-200">Recalculate standings</p><p className="mt-1 text-xs leading-5 text-slate-500">After changing scoring rules, rebuild every stored activity and weekly total. The operation is atomic but can change historical rankings.</p><button type="button" onClick={recalculate} disabled={Boolean(busy)} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-rose-500 px-3 py-2 text-xs font-black disabled:opacity-40"><RefreshCw className="h-4 w-4" />Recalculate all scores</button></div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><Heading icon={<BarChart3 />} title="Activity mix" subtitle="Approved participation by activity category." /><div className="mt-5 space-y-3">{analytics.categories.map((item) => { const max = Math.max(...analytics.categories.map((category) => category.count), 1); return <div key={item.category}><div className="flex justify-between text-sm"><span>{item.category.replaceAll('_', ' ')}</span><strong>{item.count}</strong></div><div className="mt-2 h-2 rounded-full bg-white/5"><div className="h-full rounded-full bg-orange-400" style={{ width: `${item.count / max * 100}%` }} /></div></div>; })}</div></section></div>
    <div className="grid gap-6 lg:grid-cols-2"><SystemStatusCard /><section className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><Heading icon={<FileClock />} title="Admin audit log" subtitle="Recent changes made through the control centre." /><div className="mt-5 max-h-80 divide-y divide-white/5 overflow-y-auto">{audit.length ? audit.map((item) => <div key={item.id} className="grid gap-1 py-3 text-sm sm:grid-cols-[9rem_1fr]"><span className="font-bold text-slate-300">{item.actorName}</span><span className="text-slate-400">{item.action} · {item.target}<span className="mt-1 block text-xs text-slate-600">{new Date(item.createdAt).toLocaleString('en-SG')}</span></span></div>) : <p className="py-8 text-center text-sm text-slate-500">Changes made here will appear in the audit log.</p>}</div></section></div>
  </main></div>;
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><span className="text-orange-300 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><p className="mt-4 text-3xl font-black">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>; }
function Heading({ icon, title, subtitle }: { icon: React.ReactNode; title: string; subtitle: string }) { return <div className="flex gap-3"><span className="rounded-xl bg-white/5 p-2.5 text-orange-300 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div></div>; }
function Field({ label, suffix, children }: { label: string; suffix?: string; children: React.ReactNode }) { return <label className="text-xs font-semibold text-slate-400"><span className="flex justify-between"><span>{label}</span><span className="text-slate-600">{suffix}</span></span>{children}</label>; }
function Export({ href, label, icon }: { href: string; label: string; icon?: React.ReactNode }) { return <a href={href} className="flex items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm font-bold transition hover:bg-white/5">{icon || <Download className="h-4 w-4" />}{label}</a>; }
