'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Camera, CheckCircle2, CloudOff, Copy, ImagePlus, Info, RotateCcw, Save, Sparkles, Users, X } from 'lucide-react';
import FriendMultiSelect from '@/components/FriendMultiSelect';
import AnimatedNumber from '@/components/AnimatedNumber';
import Navbar from '@/components/Navbar';
import { useDailyFriendBonus } from '@/components/useDailyFriendBonus';
import { proofDisplayHref } from '@/lib/proof-reference';
import { parseActivityDate, singaporeDate } from '@/lib/activity-date';
import { calculateActivityPoints, resolveEffectiveCategory, type ActivityCategory, type ScoringRules } from '@/lib/scoring';

type SelectableUser={id:string;name:string};
export type RecentActivitySignature={category:ActivityCategory;distance:number;occurredAt:string;status:'PENDING'|'APPROVED'|'REJECTED'};
export type LastActivityTemplate={category:ActivityCategory;distance:number;pace:number|null}|null;
type ActivityPayload={activityDate:string;category:ActivityCategory;distance?:number;pace?:number;companionUserIds?:string[];proofUrls?:string[]};
type Draft={activityDate:string;category:ActivityCategory;distance:string;pace:string;withFriend:boolean;companionUserIds:string[];proofUrls:string[];proofUrl?:string};

const MAX_FILE_SIZE=4*1024*1024;
const MAX_PROOFS=5;
const categories:Array<{value:ActivityCategory;label:string;icon:string}>=[
  {value:'RUN',label:'Run',icon:'🏃'},{value:'CYCLE',label:'Cycle',icon:'🚴'},{value:'SWIM',label:'Swim',icon:'🏊'},{value:'WALK_OR_HIKE',label:'Walk / Hike',icon:'🥾'},{value:'TROOP_GAMES',label:'Troop Games',icon:'🎯'},
];

function parsePace(value:string){if(!value.trim())return undefined;if(value.includes(':')){const [m,s]=value.split(':').map(Number);if(!Number.isFinite(m)||!Number.isFinite(s)||s<0||s>=60)return undefined;return m+s/60;}const valueNumber=Number(value);return Number.isFinite(valueNumber)?valueNumber:undefined;}
function sgDay(value:string){return new Date(value).toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'});}

async function shrinkImage(file:File):Promise<File>{
  if(file.size<1_500_000||file.type==='image/gif'||typeof createImageBitmap==='undefined')return file;
  try{
    const bitmap=await createImageBitmap(file);const longest=Math.max(bitmap.width,bitmap.height);const scale=Math.min(1,1800/longest);const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');if(!context)return file;context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
    const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/webp',0.82));if(!blob||blob.size>=file.size)return file;return new File([blob],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp',lastModified:Date.now()});
  }catch{return file;}
}

async function uploadProof(file:File,onProgress:(progress:number)=>void):Promise<string>{
  const body=new FormData();body.append('file',await shrinkImage(file));
  return new Promise<string>((resolve,reject)=>{const request=new XMLHttpRequest();request.open('POST','/api/upload');request.timeout=90000;request.upload.onprogress=progress=>{if(progress.lengthComputable)onProgress(Math.round(progress.loaded/progress.total*100));};request.onerror=()=>reject(new Error('Connection interrupted. Try the image again.'));request.ontimeout=()=>reject(new Error('Upload timed out. Try a smaller screenshot.'));request.onload=()=>{try{const data=JSON.parse(request.responseText);if(request.status<200||request.status>=300||typeof data.url!=='string')reject(new Error(typeof data.error==='string'?data.error:'Upload failed.'));else resolve(data.url);}catch{reject(new Error('Upload failed.'));}};request.send(body);});
}

export default function EnhancedActivityForm({userId,scoringRules,maintenanceMode,maintenanceMessage,recentActivities,lastActivity}:{userId:string;scoringRules:ScoringRules;maintenanceMode:boolean;maintenanceMessage:string;recentActivities:RecentActivitySignature[];lastActivity:LastActivityTemplate}){
  const router=useRouter();
  const [category,setCategory]=useState<ActivityCategory>('RUN');
  const [activityDate,setActivityDate]=useState('');const [distance,setDistance]=useState('');const [pace,setPace]=useState('');
  const [withFriend,setWithFriend]=useState(false);const [companionUserIds,setCompanionUserIds]=useState<string[]>([]);const [users,setUsers]=useState<SelectableUser[]>([]);const [usersLoading,setUsersLoading]=useState(false);const [usersLoaded,setUsersLoaded]=useState(false);const [usersError,setUsersError]=useState('');
  const [proofUrls,setProofUrls]=useState<string[]>([]);const [uploading,setUploading]=useState(false);const [uploadProgress,setUploadProgress]=useState(0);const [uploadError,setUploadError]=useState('');
  const [submitting,setSubmitting]=useState(false);const [submitError,setSubmitError]=useState('');const [online,setOnline]=useState(true);const [draftReady,setDraftReady]=useState(false);const [queued,setQueued]=useState(false);const [duplicateConfirmed,setDuplicateConfirmed]=useState(false);
  const draftKey=`kg-activity-draft:v2:${userId}`;const queueKey=`kg-activity-queue:v2:${userId}`;

  useEffect(()=>{queueMicrotask(()=>{setOnline(navigator.onLine);setActivityDate(singaporeDate());try{const saved=localStorage.getItem(draftKey);if(saved){const draft=JSON.parse(saved) as Partial<Draft>;if(categories.some(item=>item.value===draft.category))setCategory(draft.category!);setActivityDate(draft.activityDate||singaporeDate());setDistance(draft.distance||'');setPace(draft.pace||'');setWithFriend(Boolean(draft.withFriend));setCompanionUserIds(Array.isArray(draft.companionUserIds)?draft.companionUserIds.filter(id=>id!==userId):[]);const restored=Array.isArray(draft.proofUrls)?draft.proofUrls.filter((value):value is string=>typeof value==='string'&&Boolean(value)).slice(0,MAX_PROOFS):draft.proofUrl?[draft.proofUrl]:[];setProofUrls([...new Set(restored)]);}setQueued(Boolean(localStorage.getItem(queueKey)));}catch{localStorage.removeItem(draftKey);localStorage.removeItem(queueKey);}setDraftReady(true);});const onOnline=()=>setOnline(true);const onOffline=()=>setOnline(false);addEventListener('online',onOnline);addEventListener('offline',onOffline);return()=>{removeEventListener('online',onOnline);removeEventListener('offline',onOffline);};},[draftKey,queueKey,userId]);
  useEffect(()=>{if(!draftReady)return;const draft:Draft={activityDate,category,distance,pace,withFriend,companionUserIds,proofUrls};localStorage.setItem(draftKey,JSON.stringify(draft));},[activityDate,category,distance,pace,withFriend,companionUserIds,proofUrls,draftKey,draftReady]);
  useEffect(()=>{setDuplicateConfirmed(false);},[activityDate,category,distance,pace]);

  useEffect(()=>{if(!withFriend||usersLoaded)return;const controller=new AbortController();setUsersLoading(true);setUsersError('');fetch('/api/users',{cache:'no-store',signal:controller.signal}).then(async response=>{const data=await response.json().catch(()=>null);if(!response.ok||!Array.isArray(data))throw new Error('Unable to load participants.');return data as SelectableUser[];}).then(list=>{if(!controller.signal.aborted){setUsers(list);setUsersLoaded(true);setUsersLoading(false);}}).catch(error=>{if(!controller.signal.aborted){setUsersError(error instanceof Error?error.message:'Unable to load participants.');setUsersLoading(false);}});return()=>controller.abort();},[withFriend,usersLoaded]);

  useEffect(()=>{if(!online||!queued||!draftReady||maintenanceMode)return;const pending=localStorage.getItem(queueKey);if(!pending){setQueued(false);return;}setSubmitting(true);setSubmitError('Connection restored. Submitting your queued activity…');fetch('/api/activities',{method:'POST',headers:{'Content-Type':'application/json'},body:pending}).then(async response=>{const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'Queued activity could not be submitted.');localStorage.removeItem(queueKey);localStorage.removeItem(draftKey);router.push('/dashboard?activitySubmitted=true');router.refresh();}).catch(error=>{localStorage.removeItem(queueKey);setQueued(false);setSubmitError(`${error instanceof Error?error.message:'Queued activity could not be submitted.'} Your draft is still saved.`);}).finally(()=>setSubmitting(false));},[online,queued,draftReady,maintenanceMode,queueKey,draftKey,router]);

  const distanceNumber=distance?Number(distance):undefined;const paceNumber=parsePace(pace);const effectiveCategory=resolveEffectiveCategory(category,paceNumber,scoringRules);const dailyBonus=useDailyFriendBonus(userId,activityDate,effectiveCategory);
  const preview=useMemo(()=>calculateActivityPoints({category:effectiveCategory,distance:distanceNumber,pace:paceNumber,completedWithFriend:withFriend&&companionUserIds.length>0&&dailyBonus.available},scoringRules),[effectiveCategory,distanceNumber,paceNumber,withFriend,companionUserIds,dailyBonus.available,scoringRules]);
  const duplicateWarning=useMemo(()=>{if(!activityDate||!distanceNumber||distanceNumber<=0||category==='TROOP_GAMES')return '';const matches=recentActivities.filter(item=>item.status!=='REJECTED'&&item.category===effectiveCategory&&sgDay(item.occurredAt)===activityDate&&item.distance>0&&Math.abs(item.distance-distanceNumber)<=Math.max(item.distance,distanceNumber)*0.02);return matches.length?`Possible duplicate: ${matches.length} existing ${matches.length===1?'entry has':'entries have'} a similar distance for this sport on the same Singapore date.`:'';},[activityDate,distanceNumber,category,effectiveCategory,recentActivities]);
  const validationMessage=useMemo(()=>{if(!parseActivityDate(activityDate))return 'Choose a valid activity date, today or earlier.';if(category!=='TROOP_GAMES'&&(!distanceNumber||distanceNumber<=0))return 'Enter a distance greater than zero.';if(category==='WALK_OR_HIKE'&&distanceNumber&&distanceNumber<scoringRules.walkMinimumKm)return `Walks under ${scoringRules.walkMinimumKm}km do not earn points.`;if(category==='RUN'&&pace&&(paceNumber===undefined||paceNumber<=0))return 'Use a positive pace such as 6:30 or 6.5.';if(withFriend&&companionUserIds.length===0)return 'Select at least one registered friend who joined you.';if(duplicateWarning&&!duplicateConfirmed)return 'Confirm that this is a separate workout before submitting.';return '';},[activityDate,category,distanceNumber,pace,paceNumber,withFriend,companionUserIds,scoringRules.walkMinimumKm,duplicateWarning,duplicateConfirmed]);

  const useLastActivity=()=>{if(!lastActivity)return;setCategory(lastActivity.category);setDistance(lastActivity.category==='TROOP_GAMES'?'':String(lastActivity.distance||''));setPace(lastActivity.category==='RUN'&&lastActivity.pace?String(lastActivity.pace):'');setActivityDate(singaporeDate());setSubmitError('');};
  const clearForm=()=>{setCategory('RUN');setActivityDate(singaporeDate());setDistance('');setPace('');setWithFriend(false);setCompanionUserIds([]);setProofUrls([]);setDuplicateConfirmed(false);localStorage.removeItem(draftKey);localStorage.removeItem(queueKey);setQueued(false);setSubmitError('');};

  const handleFileChange=async(event:React.ChangeEvent<HTMLInputElement>)=>{const selected=Array.from(event.target.files??[]);const input=event.target;if(!selected.length)return;setUploadError('');const slots=MAX_PROOFS-proofUrls.length;if(slots<=0){setUploadError(`You can attach up to ${MAX_PROOFS} proof photos.`);input.value='';return;}const files=selected.slice(0,slots);if(selected.length>slots)setUploadError(`Only the first ${slots} photo${slots===1?'':'s'} can be added. Maximum ${MAX_PROOFS}.`);const invalid=files.find(file=>!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>MAX_FILE_SIZE);if(invalid){setUploadError(invalid.size>MAX_FILE_SIZE?`${invalid.name} is larger than 4MB.`:`${invalid.name} must be JPEG, PNG, WebP or GIF.`);input.value='';return;}if(!online){setUploadError('Reconnect before uploading proof. Your activity details are still saved.');input.value='';return;}setUploading(true);setUploadProgress(0);try{const uploaded:string[]=[];for(let index=0;index<files.length;index++){const url=await uploadProof(files[index],progress=>setUploadProgress(Math.round(((index+progress/100)/files.length)*100)));uploaded.push(url);}setProofUrls(current=>[...new Set([...current,...uploaded])].slice(0,MAX_PROOFS));}catch(error){setUploadError(error instanceof Error?error.message:'Failed to upload proof.');}finally{setUploading(false);setUploadProgress(0);input.value='';}};

  const handleSubmit=async(event:React.FormEvent)=>{event.preventDefault();setSubmitError('');if(validationMessage){setSubmitError(validationMessage);return;}const payload:ActivityPayload={activityDate,category,distance:category==='TROOP_GAMES'?undefined:distanceNumber,pace:category==='RUN'?paceNumber:undefined,companionUserIds:withFriend?companionUserIds:[],proofUrls:proofUrls.length?proofUrls:undefined};if(!online){localStorage.setItem(queueKey,JSON.stringify(payload));setQueued(true);setSubmitError('Activity queued on this device. It will submit when your connection returns.');return;}setSubmitting(true);try{const response=await fetch('/api/activities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'Failed to submit activity.');localStorage.removeItem(queueKey);localStorage.removeItem(draftKey);router.push('/dashboard?activitySubmitted=true');router.refresh();}catch(error){setSubmitError(`${error instanceof Error?error.message:'Failed to submit activity.'} Your draft remains saved on this device.`);}finally{setSubmitting(false);}};

  return <div className="min-h-screen bg-slate-950 text-white"><Navbar/><main className="page-enter mx-auto max-w-4xl px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><div className="flex items-center justify-between gap-3"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4"/>Back</Link><Link href="/activities/history" className="text-sm font-bold text-orange-300">My activities</Link></div>
    <div className="motion-card sticky top-3 z-40 mb-5 mt-4 rounded-2xl border border-orange-300/20 bg-slate-950/92 px-4 py-3 shadow-2xl backdrop-blur-xl"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-orange-400/10 text-orange-300"><Sparkles className="h-4 w-4"/></span><div><p className="text-[0.68rem] font-black uppercase tracking-[0.16em] text-orange-300">Live score preview</p><p className="text-xs text-slate-500">Base {preview.basePoints.toFixed(1)} · Friend +{preview.friendBonus.toFixed(1)}</p></div><div className="ml-auto text-right"><AnimatedNumber value={preview.totalPoints} decimals={1} className="text-3xl font-black tabular-nums" /><span className="ml-1 text-xs font-bold text-slate-500">pts</span></div></div></div>
    <form onSubmit={handleSubmit} className="motion-card space-y-5 rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-7"><header><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-300">Quick log</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black sm:text-4xl">Log an activity</h1><p className="mt-2 text-sm text-slate-400">Four short steps. Your draft saves automatically.</p></div>{lastActivity?<button type="button" onClick={useLastActivity} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-4 py-2 text-sm font-bold text-slate-300 hover:border-orange-300/30"><Copy className="h-4 w-4"/>Use last activity</button>:null}</div>{maintenanceMode?<div className="mt-4 rounded-xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm text-amber-100"><strong>Submissions paused:</strong> {maintenanceMessage}</div>:null}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-500"><span className="inline-flex items-center gap-2">{online?<Save className="h-4 w-4 text-emerald-300"/>:<CloudOff className="h-4 w-4 text-amber-300"/>}{queued?'Queued until your connection returns.':draftReady?'Draft saved on this device.':'Preparing draft…'}</span><button type="button" onClick={clearForm} className="inline-flex min-h-10 items-center gap-1 font-bold hover:text-white"><RotateCcw className="h-3.5 w-3.5"/>Reset</button></div></header>

      <Step number="1" title="Sport"><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{categories.map(item=><button key={item.value} type="button" onClick={()=>{setCategory(item.value);if(item.value!=='RUN')setPace('');if(item.value==='TROOP_GAMES')setDistance('');}} aria-pressed={category===item.value} className={`rounded-xl border px-3 py-3 text-left ${category===item.value?'border-orange-400 bg-orange-400/10':'border-white/10 bg-black/10'}`}><span className="text-xl">{item.icon}</span><span className="mt-1 block text-xs font-black">{item.label}</span></button>)}</div></Step>
      <Step number="2" title="Result"><div className="grid gap-4 sm:grid-cols-3"><label className="block"><span className="text-sm font-bold text-slate-300">Date</span><input type="date" required value={activityDate} max={singaporeDate()} onChange={e=>setActivityDate(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-3 [color-scheme:dark]"/></label>{category!=='TROOP_GAMES'?<label className="block"><span className="text-sm font-bold text-slate-300">Distance ({category==='SWIM'?'metres':'km'})</span><input type="number" min="0" step={category==='SWIM'?'1':'0.01'} required value={distance} onChange={e=>setDistance(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-3" placeholder={category==='SWIM'?'1000':'5.00'}/></label>:<div className="rounded-xl border border-violet-400/20 bg-violet-400/10 p-3 text-sm text-violet-100 sm:col-span-2">Troop Games do not need a distance.</div>}{category==='RUN'?<label className="block"><span className="text-sm font-bold text-slate-300">Pace (min/km)</span><input value={pace} onChange={e=>setPace(e.target.value)} inputMode="decimal" placeholder="6:30" className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-3"/></label>:null}</div>{effectiveCategory!==category?<p className="mt-3 rounded-xl border border-yellow-400/20 bg-yellow-400/10 p-3 text-sm text-yellow-100">This pace will score as Walk / Hike.</p>:null}{duplicateWarning?<label className="mt-3 flex items-start gap-3 rounded-xl border border-amber-400/25 bg-amber-400/10 p-3 text-sm text-amber-100"><input type="checkbox" checked={duplicateConfirmed} onChange={e=>setDuplicateConfirmed(e.target.checked)} className="mt-1 h-4 w-4 accent-amber-400"/><span><strong>{duplicateWarning}</strong><br/><span className="text-amber-100/70">Tick this only if this is a separate workout.</span></span></label>:null}</Step>
      <Step number="3" title="Friends"><label className={`flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border p-4 ${withFriend?'border-sky-400/30 bg-sky-400/10':'border-white/10 bg-black/10'}`}><input type="checkbox" checked={withFriend} onChange={e=>{setWithFriend(e.target.checked);if(!e.target.checked)setCompanionUserIds([]);}} className="h-4 w-4 accent-sky-400"/><Users className="h-5 w-5 text-sky-300"/><span className="font-bold">I completed this with friends</span></label>{withFriend?<div className="mt-3"><FriendMultiSelect users={users} value={companionUserIds} onChange={setCompanionUserIds} excludeUserId={userId} loading={usersLoading} disabled={submitting||maintenanceMode||Boolean(usersError)}/>{usersError?<p className="mt-2 text-sm text-rose-300">{usersError}</p>:null}<p className="mt-2 text-sm text-sky-200">{dailyBonus.message}</p></div>:null}</Step>
      <Step number="4" title="Proof"><div className="mb-3 flex items-center justify-between gap-3"><p className="text-sm text-slate-400">Attach up to {MAX_PROOFS} photos so reviewers can verify the full activity.</p><span className="shrink-0 text-xs font-black text-orange-300">{proofUrls.length}/{MAX_PROOFS}</span></div>{proofUrls.length?<div className="mb-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{proofUrls.map((url,index)=><div key={url} className="relative h-36 overflow-hidden rounded-2xl border border-white/10 bg-black/20"><Image src={proofDisplayHref(url)!} alt={`Uploaded proof ${index+1}`} fill unoptimized sizes="240px" className="object-contain"/><span className="absolute left-2 top-2 rounded-full bg-black/70 px-2 py-1 text-[0.65rem] font-black">{index+1}</span><button type="button" onClick={()=>setProofUrls(current=>current.filter((_,proofIndex)=>proofIndex!==index))} className="absolute right-2 top-2 rounded-full bg-rose-500 p-2" aria-label={`Remove proof ${index+1}`}><X className="h-4 w-4"/></button></div>)}</div>:null}<div className="grid gap-3 sm:grid-cols-2">{proofUrls.length<MAX_PROOFS?<label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-white/10 bg-black/10 p-4 text-center hover:border-orange-400/40"><ImagePlus className="h-7 w-7 text-slate-500"/><span className="mt-2 font-bold">{proofUrls.length?'Add photos':'Choose photos'}</span><span className="mt-1 text-xs text-slate-500">Select several screenshots at once. JPEG/PNG/WebP/GIF, max 4MB each.</span><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={handleFileChange} disabled={uploading||!online||maintenanceMode} className="hidden"/></label>:null}{proofUrls.length<MAX_PROOFS?<label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-2xl border border-white/10 px-4 text-center"><Camera className="h-6 w-6 text-slate-500"/><span className="mt-2 text-sm font-bold">Add from camera</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={handleFileChange} disabled={uploading||!online||maintenanceMode} className="hidden"/></label>:null}</div>{uploading?<div className="mt-3"><p className="text-sm text-sky-200">Uploading proofs: {uploadProgress}%</p><progress value={uploadProgress} max={100} className="mt-2 h-2 w-full accent-orange-400"/></div>:null}{uploadError?<p className="mt-3 text-sm text-rose-300">{uploadError}</p>:null}</Step>
      {validationMessage?<div className="flex items-start gap-2 rounded-xl border border-white/10 bg-black/10 p-3 text-sm text-slate-400"><Info className="mt-0.5 h-4 w-4 shrink-0 text-sky-300"/>{validationMessage}</div>:null}{submitError?<div role="alert" className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{submitError}</div>:null}<div className="flex flex-col-reverse gap-3 border-t border-white/10 pt-5 sm:flex-row sm:justify-end"><Link href="/dashboard" className="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-bold text-slate-300">Cancel</Link><button type="submit" disabled={submitting||uploading||Boolean(validationMessage)||maintenanceMode} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-orange-500 px-6 py-3 text-sm font-black hover:bg-orange-400 disabled:opacity-40"><CheckCircle2 className="h-4 w-4"/>{submitting?'Submitting…':!online?'Queue until online':'Submit for review'}</button></div>
    </form></main></div>;
}

function Step({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="border-t border-white/10 pt-5"><div className="mb-4 flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-orange-500 text-sm font-black">{number}</span><h2 className="font-black">{title}</h2></div>{children}</section>;}
