'use client';
import { useState } from 'react';
import { BarChart3, Target } from 'lucide-react';
type Week = { weekNumber: number; dateRange: string; points: number; target: number; achieved: boolean; current: boolean };
export default function WeeklyProgressChart({ weeks }: { weeks: Week[] }) {
  const [selected, setSelected] = useState<number | null>(null);
  const [showTarget, setShowTarget] = useState(true);
  const [range, setRange] = useState(7);
  const visible = weeks.slice(-range);
  const active = visible.find(w => w.weekNumber === selected) ?? visible.at(-1);
  const ceiling = Math.max(25, ...visible.flatMap(w => [w.points, showTarget ? w.target : 0])) * 1.15;
  return <section className="overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-slate-900 to-slate-950 p-5 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-3 text-lg font-black"><BarChart3 className="text-lime-300" />Weekly progress & goals</h2><p className="mt-2 text-sm text-slate-400">Week 1: 1–5 Sep · Resets Sunday, 12:00am SGT</p></div><div className="flex gap-2"><select aria-label="Weeks to display" value={range} onChange={e=>setRange(Number(e.target.value))} className="rounded-lg border border-white/15 bg-slate-900 p-2 text-sm"><option value={4}>Last 4 weeks</option><option value={7}>Last 7 weeks</option></select><button type="button" aria-pressed={showTarget} onClick={()=>setShowTarget(!showTarget)} className="flex items-center gap-2 rounded-lg border border-white/15 px-3 text-sm"><Target className="h-4 w-4" />Target {showTarget ? 'on' : 'off'}</button></div></div>
    {active ? <><div aria-live="polite" className="mt-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Week {active.weekNumber} · {active.dateRange}{active.current ? ' · Current' : ''}</p><p className="mt-2 text-4xl font-black text-white">{active.points.toFixed(1)} <span className="text-sm font-medium text-slate-400">points</span></p></div><p className={active.achieved ? 'text-emerald-300' : 'text-orange-300'}>{active.achieved ? '✓ Target achieved' : `${Math.max(0,active.target-active.points).toFixed(1)} pts to target`}<span className="mt-1 block text-xs text-slate-400">Target {active.target.toFixed(1)} · {Math.round(active.points/active.target*100)}% complete</span></p></div>
    <div className="mt-7 flex gap-2"><div aria-hidden="true" className="flex h-52 w-9 shrink-0 flex-col justify-between text-[10px] text-slate-500">{[1,.75,.5,.25,0].map(n=><span key={n}>{(ceiling*n).toFixed(0)}</span>)}</div><div className="flex min-w-0 flex-1 gap-3 overflow-x-auto pb-2">{visible.map((week,index)=><button key={week.weekNumber} type="button" onMouseEnter={()=>setSelected(week.weekNumber)} onFocus={()=>setSelected(week.weekNumber)} onClick={()=>setSelected(week.weekNumber)} aria-pressed={active.weekNumber===week.weekNumber} aria-label={`Week ${week.weekNumber}, ${week.dateRange}: ${week.points.toFixed(1)} points, target ${week.target.toFixed(1)}`} className={`min-w-24 flex-1 rounded-xl border p-2 outline-none transition-colors focus-visible:ring-2 focus-visible:ring-lime-300 ${active.weekNumber===week.weekNumber ? 'border-lime-300/40 bg-lime-300/5':'border-transparent hover:bg-white/5'}`}>
      <div className="relative flex h-48 items-end justify-center border-b border-white/20 bg-[linear-gradient(to_top,transparent_24%,#ffffff08_25%,transparent_26%,transparent_49%,#ffffff08_50%,transparent_51%,transparent_74%,#ffffff08_75%,transparent_76%)]"><div className={`weekly-chart-bar w-12 max-w-full rounded-t-lg ${week.achieved ? 'bg-gradient-to-t from-emerald-500 to-lime-300':'bg-gradient-to-t from-orange-600 to-amber-300'}`} style={{height:`${week.points/ceiling*100}%`,animationDelay:`${index*80}ms`}} />{showTarget ? <span aria-hidden="true" className="absolute inset-x-1 border-t border-dashed border-slate-300" style={{bottom:`${week.target/ceiling*100}%`}}/> : null}</div>
      <p className="mt-3 text-xs font-bold">W{week.weekNumber} · {week.points.toFixed(1)}</p><p className="mt-1 text-[10px] text-slate-400">{week.dateRange}</p></button>)}</div></div><p className="mt-4 text-xs text-slate-400">Tap or hover a week for details · Green means target achieved · Approved activities only</p></> : <p className="py-10 text-slate-400">Your challenge progress begins on 1 September.</p>}
  </section>;
}
